### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by ListenV** [dubox/jFlower#1]
使用VMWare虚拟机的用户，插件默认会使用虚拟网卡的IP来分享文件，这样就无法在其他机器上使用
将虚拟网卡禁用，再重启uTools即可本机IP，但这样太麻烦了
希望能做出改进，感谢作者！

**Comment by dubox** [comment]
貌似是有这个问题
麻烦你帮我测试一下，如果先启动有虚拟机那台上的jflower 后启动其他机器的jflower 是不是就可以用？

**Comment by ListenV** [comment]
试了，不可以，原理是这样的：
我局域网电脑的IP都是10.xx.xx.xx 这种
虚拟机是net链接的电脑网络，他的网段是192.168.xx.xx
两个网段数据不互通的，所以没法通讯

**Comment by dubox** [comment]
更新了一版，等审核通过了你试一下，然后记得反馈一下😉

**Comment by ListenV** [comment]
好的，感谢

**Comment by dubox** [comment]
问题解决了吗

**Comment by ListenV** [comment]
我再看看

**Comment by ListenV** [comment]
我发现uTools没有插件自动更新的功能

**Comment by dubox** [comment]
有的 进入插件就自动更新了

**Comment by ListenV** [comment]
好吧

**Comment by ListenV** [comment]
serving at 后面是不是当前的IP？
如果是的话，我用那个设置本机IP没作用

**Comment by ListenV** [comment]
还是有点毛病，有时候复制了图片，按Alt+空格，没有局发的选项

**Comment by dubox** [comment]
我这到没有这种情况，要不你先用用 看是经常出现还是偶尔 然后有没有什么规律啥的
