### ISSUE TITLE
关于插件列表中有两个”发送文件“选项……

### ISSUE THREAD

**Issue by iamwho-w** [dubox/jFlower#2]
为什么本机IP也会出现在列表中，这不就成了我发我自己了…？难道是我没有设置对吗？
当我在两台电脑间传送文件时,插件列表中会有两个一样的”发送文件“选项，一个发给本机，另一个才是发给另一台电脑，但是列表中也没有标注哪个是哪个，让我非常困扰。

**Comment by dubox** [comment]
可以把IP列表和插件主界面“serving at”后面的IP 截个图吗？
另外设置本机名称 可以起到区分IP的作用。

**Comment by dubox** [comment]
可以把IP列表和插件主界面“serving at”后面的IP 截个图吗？
另外设置本机名称 可以起到区分IP的作用。

**Comment by iamwho-w** [comment]
![](https://ftp.bmp.ovh/imgs/2021/04/ddd0d2d9dd93e50d.jpg)
主界面“serving at”的IP就是分别对应上图的这两个IP。
设置了本机名称，但是在超级面板的插件列表里显示不了啊…
![](https://i.bmp.ovh/imgs/2021/04/bddc9a4a79233ab9.png)

**Comment by dubox** [comment]
哦 超级面板，我还没在超级面板里用过😂😂，这个可以优化一下。
然后自己的IP正常是不显示的，你是自动识别出来的IP 还是手动设置的？

**Comment by iamwho-w** [comment]
是自动识别出来的诶
![](https://i.bmp.ovh/imgs/2021/04/956d6c6a5d580fc0.png)

**Comment by dubox** [comment]
> 是自动识别出来的诶
> ![](https://camo.githubusercontent.com/846ecb0461efa5bafe79de34d5e964b5a1fd0125a99f51f0de3d650e20184181/68747470733a2f2f692e626d702e6f76682f696d67732f323032312f30342f393536643663366135643538306663302e706e67)

👌

**Comment by dubox** [comment]
1.3.0解决
