### ISSUE TITLE
帮忙看看是什么问题

### ISSUE THREAD

**Issue by defendors** [dubox/jFlower#3]
<img width="795" alt="图片" src="https://user-images.githubusercontent.com/12707183/113260586-06025a80-9301-11eb-9eff-1a83d26563e8.png">
安装成功后，打开是这样的，“扫描网段”出现了undefined。

**Comment by dubox** [comment]
你知道你的局域网IP不，知道的话可以试一下“设置本机IP”。
这个问题我在下个版本收集下原因看看，目前我的电脑没有这个问题不太好处理。

**Comment by defendors** [comment]
设置了本机IP也不行。我有个小想法，您是不是可以搞个小的错误日志记录，也能方便查问题

**Comment by dubox** [comment]
对 我就是这意思

**Comment by dubox** [comment]
两台电脑都是一样的情况？

**Comment by tianshima** [comment]
![image](https://user-images.githubusercontent.com/12168570/113483898-37814e80-94d8-11eb-946e-0da0a632b3c7.png)
主机名称不要设置中文名
@dubox 下个版本会修复吗

**Comment by tianshima** [comment]
@defendors 主机名称不要设置中文名
@dubox 下个版本会修复吗

**Comment by dubox** [comment]
> @defendors 主机名称不要设置中文名
> @dubox 下个版本会修复吗

是因为中文名导致的吗，是的话下个版本肯定会修复。

**Comment by defendors** [comment]
我改了一下，改成英文后就可以了，确实是中文名的问题。因为我电脑名称就有中文，默认主机名就是中文。

**Comment by dubox** [comment]
1.3.0解决
