### ISSUE TITLE
有关多网段

### ISSUE THREAD

**Issue by haohaolalahao** [dubox/jFlower#6]
![image](https://user-images.githubusercontent.com/30471665/114808437-d1030700-9dda-11eb-86d5-12e6e40c16a6.png)
![image](https://user-images.githubusercontent.com/30471665/114808530-0c9dd100-9ddb-11eb-8f71-61547e779d5e.png)

IP第二个字段不在一起的局域网环境能否有办法解决？

**Comment by dubox** [comment]
不同网段的局域网必须是通的，插件没有办法解决网不通的问题

**Comment by dubox** [comment]
哦 没仔细看图 不好意思
这个可以支持一下。
可以把前面三段都做成填的，但是扫描还是只能扫描最后一段

**Comment by haohaolalahao** [comment]
好的呢，谢谢作者，因为学校环境比较特殊，分配网段比较多。

**Comment by dubox** [comment]
1.3.1
