### ISSUE TITLE
无法发现局域网内其他安装了utools和局发的电脑

### ISSUE THREAD

**Issue by laodao** [dubox/jFlower#7]
无法发现局域网内其他安装了utools和局发的电脑，如果通过http://ip:8891/detect，都是可以打开对方的。
显示jFlower （局发）is running

**Comment by dubox** [comment]
两边识别的ip都是对的吗？ 
无法发现是指：输入文字 没有出现“发送到xxx”的选项？

**Comment by dubox** [comment]
两边识别的ip都是对的吗？ 
无法发现是指：输入文字 没有出现“发送到xxx”的选项？

**Comment by laodao** [comment]
可能是我操作问题，后面可以了。
